[pytest]
testpaths = tests
pythonpath = .
addopts = -ra
filterwarnings =
    ignore:Using `httpx` with `starlette.testclient` is deprecated
    ignore:No path_separator found in configuration:DeprecationWarning
