"""create book text tables

Revision ID: a731331a8b73
Revises: 62072b4b4930
Create Date: 2026-10-03 11:39:01.055567

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a731331a8b73'
down_revision: Union[str, None] = '62072b4b4930'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('volumes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.Enum('main', 'short_story_collection', name='volume_kind'), nullable=False),
    sa.Column('number', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('file_name', sa.String(length=255), nullable=False),
    sa.Column('file_size', sa.BigInteger(), nullable=False),
    sa.Column('file_sha256', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('kind', 'number')
    )
    op.create_table('book_parts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('volume_id', sa.Integer(), nullable=False),
    sa.Column('ordinal', sa.Integer(), nullable=False),
    sa.Column('kind', sa.Enum('story', 'afterword', 'preview', 'front_matter', 'toc', 'copyright', 'newsletter', 'ad', name='book_part_kind'), nullable=False),
    sa.Column('part_type', sa.String(length=32), nullable=False),
    sa.Column('number', sa.Integer(), nullable=True),
    sa.Column('label', sa.String(length=64), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('subtitle', sa.String(length=255), nullable=True),
    sa.Column('source_files', sa.ARRAY(sa.Text()), nullable=False),
    sa.ForeignKeyConstraint(['volume_id'], ['volumes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('volume_id', 'ordinal')
    )
    op.create_index(op.f('ix_book_parts_volume_id'), 'book_parts', ['volume_id'], unique=False)
    op.create_table('book_sections',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('part_id', sa.Integer(), nullable=False),
    sa.Column('ordinal', sa.Integer(), nullable=False),
    sa.Column('number', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['part_id'], ['book_parts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('part_id', 'ordinal')
    )
    op.create_index(op.f('ix_book_sections_part_id'), 'book_sections', ['part_id'], unique=False)
    op.create_table('book_paragraphs',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('volume_id', sa.Integer(), nullable=False),
    sa.Column('section_id', sa.Integer(), nullable=False),
    sa.Column('seq', sa.Integer(), nullable=False),
    sa.Column('ordinal', sa.Integer(), nullable=False),
    sa.Column('kind', sa.Enum('text', 'scene_break', 'ornament', name='book_paragraph_kind'), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('source_file', sa.String(length=255), nullable=False),
    sa.Column('source_block', sa.Integer(), nullable=False),
    sa.Column('page', sa.String(length=16), nullable=True),
    sa.ForeignKeyConstraint(['section_id'], ['book_sections.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['volume_id'], ['volumes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('volume_id', 'seq')
    )
    op.create_index(op.f('ix_book_paragraphs_section_id'), 'book_paragraphs', ['section_id'], unique=False)
    # ### end Alembic commands ###
    # Section text in reading order, for chunking; scene breaks stay in as "* * *" lines
    op.execute("""
        CREATE VIEW book_section_texts AS
        SELECT s.id AS section_id,
               pt.volume_id,
               pt.id AS part_id,
               pt.kind AS part_kind,
               pt.ordinal AS part_ordinal,
               s.ordinal AS section_ordinal,
               s.number AS section_number,
               string_agg(bp.text, E'\n\n' ORDER BY bp.ordinal) AS text,
               count(*) AS paragraph_count,
               min(bp.seq) AS first_seq,
               max(bp.seq) AS last_seq
        FROM book_sections s
        JOIN book_parts pt ON pt.id = s.part_id
        JOIN book_paragraphs bp ON bp.section_id = s.id
        GROUP BY s.id, pt.id
    """)


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("DROP VIEW IF EXISTS book_section_texts")
    op.drop_index(op.f('ix_book_paragraphs_section_id'), table_name='book_paragraphs')
    op.drop_table('book_paragraphs')
    op.drop_index(op.f('ix_book_sections_part_id'), table_name='book_sections')
    op.drop_table('book_sections')
    op.drop_index(op.f('ix_book_parts_volume_id'), table_name='book_parts')
    op.drop_table('book_parts')
    op.drop_table('volumes')
    sa.Enum(name='book_paragraph_kind').drop(op.get_bind(), checkfirst=True)
    sa.Enum(name='book_part_kind').drop(op.get_bind(), checkfirst=True)
    sa.Enum(name='volume_kind').drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
