"""create qa conversation tables

Revision ID: 5c4fed8722a0
Revises: 5c1e7b9d2f40
Create Date: 2026-10-04 05:24:29.219428

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5c4fed8722a0'
down_revision: Union[str, None] = '5c1e7b9d2f40'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('qa_conversations',
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_qa_conversations_user_id'), 'qa_conversations', ['user_id'], unique=False)
    op.create_table('qa_messages',
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('conversation_id', sa.Uuid(), nullable=False),
    sa.Column('role', sa.Enum('user', 'assistant', name='qa_message_role'), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('max_volume', sa.Integer(), nullable=True),
    sa.Column('found', sa.Boolean(), nullable=True),
    sa.Column('mode', sa.String(length=32), nullable=True),
    sa.Column('model', sa.String(length=128), nullable=True),
    sa.Column('sources', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('trace', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('usage', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('timings_ms', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('feedback', sa.SmallInteger(), nullable=True),
    sa.Column('feedback_comment', sa.Text(), nullable=True),
    sa.Column('feedback_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('feedback IN (-1, 1)', name='ck_qa_messages_feedback'),
    sa.ForeignKeyConstraint(['conversation_id'], ['qa_conversations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_qa_messages_conversation_created', 'qa_messages', ['conversation_id', 'created_at'], unique=False)
    op.create_index('ix_qa_messages_feedback', 'qa_messages', ['feedback'], unique=False, postgresql_where=sa.text('feedback IS NOT NULL'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_qa_messages_feedback', table_name='qa_messages', postgresql_where=sa.text('feedback IS NOT NULL'))
    op.drop_index('ix_qa_messages_conversation_created', table_name='qa_messages')
    op.drop_table('qa_messages')
    op.drop_index(op.f('ix_qa_conversations_user_id'), table_name='qa_conversations')
    op.drop_table('qa_conversations')
    sa.Enum(name='qa_message_role').drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
