"""create qa requests table

Revision ID: d0dfbf5e9554
Revises: 5c4fed8722a0
Create Date: 2026-10-04 07:33:11.842826

"""
import os
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd0dfbf5e9554'
down_revision: Union[str, None] = '5c4fed8722a0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('qa_requests',
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=True),
    sa.Column('message_id', sa.Uuid(), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('error_kind', sa.String(length=32), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('question_chars', sa.Integer(), nullable=False),
    sa.Column('mode', sa.String(length=32), nullable=True),
    sa.Column('degraded', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('output_blocked', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('model', sa.String(length=128), nullable=True),
    sa.Column('llm_calls', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('tools', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('prompt_tokens', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('completion_tokens', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('cost_usd', sa.Numeric(precision=12, scale=6), server_default=sa.text('0'), nullable=False),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.Column('found', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['message_id'], ['qa_messages.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_qa_requests_created', 'qa_requests', ['created_at'], unique=False)
    op.create_index('ix_qa_requests_user_created', 'qa_requests', ['user_id', 'created_at'], unique=False)
    # ### end Alembic commands ###

    # Answers stored before this table existed, so reports and today's limits include them.
    # Cost uses the prices configured now (LLM_PRICE_*_PER_MTOK, same defaults as src/core/config.py)
    op.execute(sa.text("""
        INSERT INTO qa_requests (user_id, message_id, status, error_kind, error, question_chars, mode, model,
                                 llm_calls, tools, prompt_tokens, completion_tokens, cost_usd, latency_ms,
                                 found, created_at, finished_at)
        SELECT c.user_id, a.id,
               CASE WHEN a.error IS NOT NULL THEN 'error' WHEN a.found THEN 'answered' ELSE 'not_found' END,
               CASE WHEN a.error IS NOT NULL THEN 'error' END, a.error,
               coalesce((SELECT length(q.content) FROM qa_messages q
                         WHERE q.conversation_id = a.conversation_id AND q.role = 'user'
                           AND q.created_at <= a.created_at ORDER BY q.created_at DESC LIMIT 1), 0),
               a.mode, a.model,
               CASE WHEN a.error IS NOT NULL THEN 0
                    ELSE greatest(1, (SELECT count(*) FROM jsonb_array_elements(coalesce(a.trace, '[]')) t
                                      WHERE t ? 'llm')) END,
               (SELECT jsonb_agg(t->'tool') FROM jsonb_array_elements(coalesce(a.trace, '[]')) t WHERE t ? 'tool'),
               coalesce((a.usage->>'prompt_tokens')::int, 0),
               coalesce((a.usage->>'completion_tokens')::int, 0),
               (coalesce((a.usage->>'prompt_tokens')::int, 0) * :pin
                + coalesce((a.usage->>'completion_tokens')::int, 0) * :pout) / 1000000.0,
               coalesce((a.timings_ms->>'retrieval')::int, 0) + coalesce((a.timings_ms->>'llm')::int, 0),
               a.found, a.created_at, a.created_at
        FROM qa_messages a JOIN qa_conversations c ON c.id = a.conversation_id
        WHERE a.role = 'assistant'
    """).bindparams(pin=float(os.getenv("LLM_PRICE_INPUT_PER_MTOK", "0.5")),
                    pout=float(os.getenv("LLM_PRICE_OUTPUT_PER_MTOK", "3"))))


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_qa_requests_user_created', table_name='qa_requests')
    op.drop_index('ix_qa_requests_created', table_name='qa_requests')
    op.drop_table('qa_requests')
    # ### end Alembic commands ###
